baseurl = "/"
languageCode = "pt-br"
languageLang = "pt"
title = "Inicio"

disqusShortname = "investidordevalor"

enableRobotsTXT = true
canonifyURLs = true

[author]
name = "Investidor de Valor"

[taxonomies]
category = "categories"
tag = "tags"